## **Arrays** são estruturas de dados semelhantes às listas do Python, mas não tão flexíveis. Em um **array todos os elementos devem ser de um mesmo tipo, tipicamente numérico, como int ou float**. Além disso, **o tamanho de um array não pode ser modificado**, ao contrário de listas que podem crescer dinamicamente.

O **NumPy** define a **classe ndarray** (N-Dimensional Array) para encapsular **arrays de n dimensões**. Os arrays do NumPy tem tamanho fixo, assim, para se mudar o tamanho de um ndarray, cria-se um novo array e o original é removido.

Um array em NumPy é uma tabela multidimensional de elementos do mesmo tipo, indexados por uma tupla de inteiros positivos. As dimensões são chamadas de eixos (axes).

A classe básica é o ndarray que também tem o apelido de array. Note que o numpy.array é diferente do tipo nativo do Python array.array que só manipula arrays de uma dimensão e apresenta menos funcionalidades.

**Principais atributos da ndarray**

**ndarray.ndim**: um inteiro que corresponde ao número de eixos (dimensões) do array.

**ndarray.shape**: uma tupla contendo as dimensões do array, ou comprimento do array em cada eixo. O comprimento dessa tupla é o número de dimensões ndim.

**ndarray.size**: número total de elementos no array. Equivale ao produto dos elementos de shape.

**ndarray.dtype**: descreve o tipo dos elementos do array. Além dos tipos nativos do Python, como int e float, o NumPy oferece seus próprios tipos, como numpy.int32, numpy.int16, numpy.float64, etc.

**ndarray.itemsize**: indica o tamanho de cada elemento do array em bytes. Por exemplo, para elementos do tipo numpy.float64, o tamanho em 8 bytes (= 64 bits / 8 bits).

In [ ]:
import numpy as np
'''uma lista (matriz 2x3):'''
a = [[1,2,3],[4,5,6]]
'''um array criado a partir desta lista'''
b = np.array(a)
print(a)
print(b)
print(type(a))
print(type(b))

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
'''posso criar o array especificando o tipo dos seus elementos'''
'''uma lista (matriz 2x3):'''
a = [[1,2,3],[4,5,6]]
'''um array criado a partir desta lista, com elementos do tipo float'''
b = np.array(a,float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np
'''atributos da classe ndarray'''
'''(a) é um array bidimensional, tem 3 linhas e 2 colunas (3x2)'''
a = np.array([[1,2],[4,5],[7,8]])
print(a)
'''o atributo ndim mostra o número de dimensões do array'''
print('o array tem:',a.ndim,' dimensões')
'''o atributo shape mostra o tamanho de cada dimensão do array'''
print('número de linhas e colunas do array:',a.shape)
'''o atributo size mostra o número de elemento do array'''
print('o array tem:',a.size,'elementos.')


[[1 2]
 [4 5]
 [7 8]]
o array tem: 2  dimensões
número de linhas e colunas do array: (3, 2)
o array tem: 6 elementos.


In [ ]:
import numpy as np
a = np.array([[1,2],[4,5],[7,8]])
print(a)
print('o array tem:',a.ndim,' dimensões')
print('nº de linhas e colunas:',a.shape)
print('o array tem:',a.size,'elementos.')

[[1 2]
 [4 5]
 [7 8]]
o array tem: 2  dimensões
nº de linhas e colunas: (3, 2)
o array tem: 6 elementos.


# OPERAÇÕES COM **NP.ARRAY**

In [ ]:
import numpy as np
a = np.array([2,3,4])
b = np.array([1,1,1])
c = a + b
print (c)

[3 4 5]
